Repository BamaCharanChhandogi/GitFinder, pull requests merged in 2024-10, with the labels that each got.

#9 Update README.md
  README.md
Labels: gssoc, level1

#17 #Add Code_Of_Conduct.md
  Code_Of_Conduct.md
Labels: gssoc, level1

#28 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: gssoc, level1, gssoc-ext

#29 Updated Explore.jsx
  src/pages/Explore.jsx
Labels: gssoc, level2, gssoc-ext, hactoberfest-accepted

#33 Added anchor tag for redirect to blogAuthor
  src/Components/Blog/BlogPost.jsx
Labels: gssoc, level2, gssoc-ext

#34 Update README.md with env details
  README.md
Labels: level1, gssoc-ext

#13 Updated "Let's Go" button emoji to 🚀 for better alignment with brand and purpose (Issue #7)
  src/Components/Landing/Hero.jsx
  src/firebase.js
Labels: gssoc-ext

#14 added a "Star us on GitHub" button: (This PR resolves Issue #6)
  src/Components/Landing/Hero.jsx
Labels: level1, gssoc-ext

#42 #Add greetings.yml
  .github/workflows/greetings.yml
Labels: level1, gssoc-ext

#43 Gif Change (issue #15)
  src/pages/Explore.jsx
Labels: level1, gssoc-ext

#48 Horizontal Scrool removed from Profile Page Issue no #30 Resolved
  src/Components/RepoInfo.jsx
Labels: level2, gssoc-ext

#60 Enhance README with Tech Stack Icons, Visuals, and Contributor Image
  README.md
  package-lock.json
  package.json
  src/assets/ReadMeAssests/GSSoC-Ext.png
  src/assets/ReadMeAssests/Hacktoberfest.png
  src/assets/ReadMeAssests/Login.png
Labels: level2, gssoc-ext

#61 Fixed Likes Logic for Blog and Post
  src/Components/Blog/BlogPost.jsx
  src/Components/Blog/CreateBlogPost.jsx
  src/Components/post/Post.jsx
Labels: gssoc-ext, level3

#83 Done some enhancements in the document and also added some new sections
  CONTRIBUTING.md
Labels: level2, gssoc-ext

#80 Issue:#73: fix: Mobile responsiveness for home and blog page.
  package-lock.json
  package.json
  src/pages/BlogPage.jsx
  src/pages/Home.jsx
Labels: level2, gssoc-ext

#91 update description of git finder
  src/pages/About.jsx
Labels: level1, gssoc-ext, hactoberfest-accepted
